(global-set-key (kbd "C-x o") 'ace-window)
(global-set-key (kbd "C-z") 'undo)
(global-set-key (kbd "C-/") 'comment-or-uncomment-region)
(global-set-key (kbd "C->") 'paredit-forward-slurp-sexp)
(global-set-key (kbd "C-<") 'paredit-backward-slurp-sexp)
