(defun buffer-state-* ()
  (cond (buffer-read-only "·")
        ((buffer-modified-p) "*")
        (t "-")))

(defun buffer-state-+ ()
  (cond ((buffer-modified-p) "*")
        (buffer-read-only "·")
        (t "-")))

;; TODO: Handle overflow
(defun aligned-mode-line (left-pad left center right right-pad)
  (let* ((left-pad-f  `(format-mode-line ,left-pad))
         (left-f      `(format-mode-line ,left))
         (center-f    `(format-mode-line ,center))
         (right-f     `(format-mode-line ,right))
         (right-pad-f `(format-mode-line ,right-pad))
         (available `(/ (- (window-width) (length ,center-f)) 2))
         (available `(if (cl-oddp ,available)
                         (+ 1 ,available)
                         ,available))
         (left-space  `(make-list (- ,available (length ,left-f) (length ,left-pad-f)) " "))
         (right-space `(make-list (- ,available (length ,right-f) (length ,right-pad-f)) " ")))
    (setq-default mode-line-format
                  `((:eval ,left-pad)
                    (:eval ,left)
                    (:eval ,left-space)
                    (:eval ,center)
                    (:eval ,right-space)
                    (:eval ,right)
                    (:eval ,right-pad)))))
